# Generated by Django 2.2.13 on 2020-08-06 14:32

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.tags.set(article.tags_old.all())


def rollback_transfer(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.tags_old.set(article.tags.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200806_2030'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
