# Generated by Django 2.2.13 on 2020-10-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20201008_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Счётчик лайков'),
        ),
    ]
